### PR TITLE
Bottom bar improvements - Issue #4

### PR DESCRIPTION
**Pull request by u1035**
I've added style for hotkey text with smaller text font and opacity=0.5, and aligned icons. Please have a look, are this changes appropriate?

ca4

### CODE REVIEW

**Comment by IngvarX** [comment]
Hello! Thank you for your PR!  Two minor issues I've noticed:

1) You converted spaces to tabs in your commit, please undo. Let's keep spaces everywhere :smile: 
2) I think in #4 hotkey text is moved down by few pixels, what do you think?
image
image

**Comment by u1035** [comment]
Sorry for spaces - I didn't noticed when my Studio did it.
I'll check hotkey placement now.

**Comment by u1035** [comment]
At this screenshot hotkeys text moved 2 pixels down - does it look better?

(On top is same screenshot, just with lines - i don't trust my eyes, so draw line to see alignment)

ca5

**Comment by IngvarX** [comment]
Yes, it's better. Also please remove missing tabs in Common.xaml

**Comment by u1035** [comment]
Forgot them. Done)

**Comment by IngvarX** [comment]
Thanks, I'm merging it

**Pull request merged**
